export default [
	{
		id:1,
		title: 'App Development',
		description: '26 job positions',
		deadline: 'monday 3 jun',
		completed: false,
	},
	{
		id:2,
		title: 'Arts & Entertainment',
		description: '9 job positions',
		deadline: 'monday 3 jun',
		completed: true,
	},
	{
		id:3,
		title: 'Accounting',
		description: '11 job positions',
		deadline: 'monday 3 jun',
		completed: false,
	},
	{
		id:4,
		title: 'UI Designer',
		description: '37 job positions',
		deadline: 'monday 3 jun',
		completed: false,
	},
	{
		id:5,
		title: 'Apps',
		description: '2 job positions',
		deadline: 'monday 3 jun',
		completed: true,
	},
	{
		id:6,
		title: 'Content Writer',
		description: '10 job positions',
		deadline: 'monday 3 jun',
		completed: false,
	},
	{
		id:7,
		title: 'Analytics',
		description: '14 job positions',
		deadline: 'monday 3 jun',
		completed: true,
	},
	{
		id:8,
		title: 'Management',
		description: '14 job positions',
		deadline: 'monday 3 jun',
		completed: false,
	},
];
